CREATE TABLE  issue (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
category INT NOT NULL ,
description VARCHAR( 255 ) NOT NULL ,
lat VARCHAR( 255 ) NOT NULL ,
lng VARCHAR( 255 ) NOT NULL ,
image_src VARCHAR( 255 ) NULL,
createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
fixed BOOLEAN NOT NULL DEFAULT false
) ENGINE = INNODB CHARACTER SET utf8 COLLATE utf8_unicode_ci;